#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

OWNER="StGerman"
REPO="crew"
ISSUE="64"
LABEL="crew"
KEY_PATH="$HOME/.config/crew/crew-app.pem"
ENV_FILE="$HOME/.config/crew/crew-app.env"
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

TOTAL_STAGES=5

# This machine runs bash 3.2, where `set -u` makes an empty array's expansion an
# unbound-variable error. The library's finish() reads three arrays that can
# legitimately stay empty, so it is overridden here rather than edited upstream.
finish() {
  _clear
  printf '\n%s%s  ✓ Crew identity configured%s\n' "$BOLD" "$GREEN" "$RESET"
  note "config:      $ENV_FILE"
  note "private key: $KEY_PATH"
  note "dispatch:    label '$LABEL' on an issue"
  printf '\n'
  say "${BOLD}Next:${RESET} issue #$ISSUE is the code that consumes these."
  note "Nothing reads $ENV_FILE yet — the config keys land with #$ISSUE."
  printf '\n'
}

# b64url encodes stdin for a JWT segment.
b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# app_jwt mints a short-lived JWT signed with the App private key.
app_jwt() {
  local now header payload sig
  now=$(date +%s)
  header=$(printf '%s' '{"alg":"RS256","typ":"JWT"}' | b64url)
  payload=$(printf '{"iat":%s,"exp":%s,"iss":"%s"}' "$((now - 60))" "$((now + 540))" "$CREW_APP_ID" | b64url)
  sig=$(printf '%s.%s' "$header" "$payload" | openssl dgst -sha256 -sign "$KEY_PATH" -binary | b64url)
  printf '%s.%s.%s' "$header" "$payload" "$sig"
}

banner "Crew identity setup — one GitHub App, no second account"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Register the GitHub App"
say "One account, and it is the one that authors every write."
note "There is no companion machine user: an app[bot] cannot be an issue assignee,"
note "and a marker account cannot be read-only on a personal repo. Dispatch is a"
note "label instead — stage 5 creates it."
printf '\n'
open_url "https://github.com/settings/apps/new"
step "Name it Crewd. App names are globally unique — 'Crew Orchestrator' is the fallback."
step "Homepage URL: https://github.com/$OWNER/$REPO"
step "Webhook: UNCHECK 'Active'. Nothing here listens for webhooks."
printf '\n'
say "${BOLD}Repository permissions${RESET} — set exactly these, and nothing more:"
note "  Contents .......... Read and write   (push branches)"
note "  Issues ............ Read and write   (comments, state:* labels)"
note "  Pull requests ..... Read and write   (open PRs, reply on threads)"
note "  Commit statuses ... Read-only        (delivery reads CI)"
note "  Checks ............ Read-only        (delivery reads CI)"
note "  Metadata .......... Read-only        (mandatory, pre-selected)"
printf '\n'
warn "Grant nothing else. The narrow grant is half the point of using an App:"
note "it cannot merge, cannot administer, and cannot approve its own pull request."
step "'Where can this GitHub App be installed?' → Only on this account."
step "Click Create GitHub App."
printf '\n'
ask CREW_APP_ID "App ID (shown at the top of the App's settings page):"
[[ "$CREW_APP_ID" =~ ^[0-9]+$ ]] || { warn "App ID should be numeric"; exit 1; }
write_env CREW_APP_ID "$CREW_APP_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Generate and place the private key"
say "The key is the App's credential. It goes outside this repository."
warn "Never put it in ~/Code/symphony: agents run there with bypassPermissions."
printf '\n'
step "Still on the App's settings page, scroll to 'Private keys'."
step "Click 'Generate a private key'. A .pem file downloads."
printf '\n'
DEFAULT_PEM=$(ls -t "$HOME/Downloads"/*.private-key.pem "$HOME/Downloads"/*.pem 2>/dev/null | head -1 || true)
if [[ -n "$DEFAULT_PEM" ]]; then
  note "newest .pem in ~/Downloads: $DEFAULT_PEM"
fi
printf '  %sPath to the downloaded .pem%s %s[Enter for the one above]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
read -r PEM_SRC || true
[[ -z "$PEM_SRC" ]] && PEM_SRC="$DEFAULT_PEM"
PEM_SRC="${PEM_SRC/#\~/$HOME}"
if [[ ! -f "$PEM_SRC" ]]; then
  warn "no file at: $PEM_SRC"
  exit 1
fi
# Validate before moving. A rejected file left at KEY_PATH is worse than none:
# the next run finds it and treats the key as already installed.
if openssl rsa -in "$PEM_SRC" -noout -check >/dev/null 2>&1; then
  printf '  %s✓ verified%s it is a valid RSA private key\n' "$GREEN" "$RESET"
else
  warn "openssl could not read that as an RSA private key — wrong file?"
  note "nothing was moved; $PEM_SRC is where it was"
  exit 1
fi
mv "$PEM_SRC" "$KEY_PATH"
chmod 600 "$KEY_PATH"
printf '  %s✓ installed%s %s (mode 600)\n' "$GREEN" "$RESET" "$KEY_PATH"
write_env CREW_PRIVATE_KEY_PATH "$KEY_PATH"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Install the App on $OWNER/$REPO"
say "Registering an App does not give it access to anything. Installing does."
open_url "https://github.com/settings/apps"
step "Click your Crewd app → 'Install App' in the left sidebar."
step "Click Install next to $OWNER."
step "Choose 'Only select repositories' → pick $REPO → Install."
pause "Press Enter once it is installed"
printf '\n'
say "Asking GitHub for the installation id..."
JWT=$(app_jwt)
INSTALLS=$(curl -sS -H "Authorization: Bearer $JWT" -H "Accept: application/vnd.github+json" \
  https://api.github.com/app/installations)
# Pick the installation on OWNER, not simply the first: an App can be installed
# on several accounts, including the one that owns it, and only one of those can
# see this repository.
CREW_INSTALLATION_ID=$(printf '%s' "$INSTALLS" | python3 -c "
import json,sys
try: d = json.load(sys.stdin)
except Exception: sys.exit()
if isinstance(d, list):
    for i in d:
        if i.get('account', {}).get('login', '').lower() == '$OWNER'.lower():
            print(i['id']); break
" 2>/dev/null || true)
if [[ -n "$CREW_INSTALLATION_ID" ]]; then
  printf '  %s✓ found%s installation id %s\n' "$GREEN" "$RESET" "$CREW_INSTALLATION_ID"
else
  warn "could not read it back — GitHub said:"
  printf '%s\n' "$INSTALLS" | head -5
  ask CREW_INSTALLATION_ID "Installation id (the number at the end of the install settings URL):"
fi
write_env CREW_INSTALLATION_ID "$CREW_INSTALLATION_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify a real installation token"
say "Proving the key, the app id and the installation actually work together."
printf '\n'
JWT=$(app_jwt)
TOKEN_JSON=$(curl -sS -X POST \
  -H "Authorization: Bearer $JWT" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/app/installations/$CREW_INSTALLATION_ID/access_tokens")
TOKEN=$(printf '%s' "$TOKEN_JSON" | grep -o '"token"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\([^"]*\)"$/\1/' || true)
EXPIRY=$(printf '%s' "$TOKEN_JSON" | grep -o '"expires_at"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\([^"]*\)"$/\1/' || true)
if [[ -z "$TOKEN" ]]; then
  warn "no token came back. GitHub said:"
  printf '%s\n' "$TOKEN_JSON" | head -10
  exit 1
fi
printf '  %s✓ minted%s an installation token, expires %s\n' "$GREEN" "$RESET" "$EXPIRY"
note "That expiry is why issue #$ISSUE cannot keep holding the token in a String."
printf '\n'
# Ask about this repository directly. /installation/repositories pages at 30, so
# a scan of its first page reports a false negative on an account with more.
REPO_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
  -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO")
if [[ "$REPO_CODE" == "200" ]]; then
  printf '  %s✓ the token can reach%s %s/%s\n' "$GREEN" "$RESET" "$OWNER" "$REPO"
else
  warn "GET /repos/$OWNER/$REPO returned $REPO_CODE — was the install scoped elsewhere?"
fi
SELECTION=$(curl -sS -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/installation/repositories?per_page=1" \
  | grep -o '"total_count"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$' || true)
if [[ -n "$SELECTION" && "$SELECTION" -gt 1 ]]; then
  printf '\n'
  warn "this installation covers $SELECTION repositories, not just $REPO."
  note "The App holds contents:write on every one of them. Narrow it at"
  note "    https://github.com/settings/installations"
fi
ISSUES_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
  -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO/issues?state=open&per_page=1")
if [[ "$ISSUES_CODE" == "200" ]]; then
  printf '  %s✓ Issues permission works%s (GET issues → 200)\n' "$GREEN" "$RESET"
else
  warn "GET issues returned $ISSUES_CODE — check the Issues permission on the App"
fi
unset TOKEN
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The dispatch label, and recording it"
say "An issue is handed to Crew by carrying the '$LABEL' label."
printf '\n'
if gh label list --repo "$OWNER/$REPO" --search "$LABEL" 2>/dev/null | grep -q "^$LABEL"; then
  printf '  %s✓%s label '\''%s'\'' already exists\n' "$GREEN" "$RESET" "$LABEL"
else
  if gh label create "$LABEL" --repo "$OWNER/$REPO" \
       --color 0E8A16 --description "Ready for the Crew orchestrator to work" >/dev/null 2>&1; then
    printf '  %s✓ created%s label '\''%s'\''\n' "$GREEN" "$RESET" "$LABEL"
  else
    warn "could not create the label; create it by hand:"
    note "    gh label create $LABEL --repo $OWNER/$REPO --color 0E8A16"
  fi
fi
printf '\n'
write_env CREW_OWNER "$OWNER"
write_env CREW_REPO "$REPO"
write_env CREW_DISPATCH_LABEL "$LABEL"
chmod 600 "$ENV_FILE"
printf '  %s✓ mode 600%s %s\n' "$GREEN" "$RESET" "$ENV_FILE"
printf '\n'
say "${BOLD}Paste into symphony.github.toml once #$ISSUE lands its config keys:${RESET}"
printf '\n'
printf '    [tracker]\n'
printf '    kind = "github"\n'
printf '    owner = "%s"\n' "$OWNER"
printf '    repo = "%s"\n' "$REPO"
printf '    dispatch_label = "%s"\n' "$LABEL"
printf '    app_id = %s\n' "$CREW_APP_ID"
printf '    installation_id = %s\n' "$CREW_INSTALLATION_ID"
printf '    private_key_path = "%s"\n' "$KEY_PATH"
printf '\n'
if confirm "Post a comment on issue #$ISSUE recording that the App exists?"; then
  gh issue comment "$ISSUE" --repo "$OWNER/$REPO" --body "$(cat <<EOF
The App now exists, so the code half of this issue is unblocked.

- App id \`$CREW_APP_ID\`, installation \`$CREW_INSTALLATION_ID\` on \`$OWNER/$REPO\`.
  Permissions: contents RW, issues RW, pull requests RW, statuses RO, checks RO, metadata RO.
  No merge permission, by design.
- Private key at \`$KEY_PATH\` (mode 600), outside the repository. Config values in
  \`$ENV_FILE\`.
- Dispatch label \`$LABEL\` exists on the repository. No second account was created.

Verified by hand: a minted installation token reads the repo and its issues, and expires
in an hour — which is the constraint behind "the token cannot stay a \`String\`" above.
EOF
)" >/dev/null && printf '  %s✓ commented on%s #%s\n' "$GREEN" "$RESET" "$ISSUE"
fi

finish
